jenkins/files/nginx.conf

This way, jenkins doesn't have the exclusivity on Nginx.

Enable configuring jenkins server_name

---

.travis.yml
test/pillar/example.sls
test/pillar/top.sls

This should let you know easily if a PR breaks anything !
See it in action: https://travis-ci.org/jpic/jenkins-formula
It's interresting to see that jenkins.nginx includes nginx but not jenkins. If it did, it would look a bit cleaner (ie. we could replace `jenkins,jenkins.nginx` by just `jenkins.nginx` in this PR).

Added .travis.yml

---

jenkins/files/nginx.conf
jenkins/init.sls
jenkins/map.jinja
pillar.example

* use `map.jinja` to store default configuration values for the main state and the nginx state
* changes a few things regarding jenkins user (home directory, account type) to make the default setup more "standard"

Use map.jinja and a few other changes

---

jenkins/map.jinja
jenkins/nginx.sls

The proper fix for this is to refactor out common elements in `map.jinja` with distro-specific overrides, but I'm not quite sure how to do that idiomatically. Suggestions welcome.

#32 fix: Allowing nginx user/group to be overriden

---

.travis.yml

Prevent a commit from being built twice:
- because it's a PR,
- **because it's a branch**.
After this commit, the second condition doesn't apply anymore.

Prevent duplicate builds on travis.

---

.travis.yml
jenkins/map.jinja
jenkins/plugins.sls
pillar.example

Extending @jpic's PR #24 with support for:
- Authenticated `jenkins-cli` 
- Plugin disabling
- Simplifying `plugins.sls` refactors

Fix #23: Provision jenkins plugins

---

jenkins/map.jinja
jenkins/plugins.sls

Continuation from #31. Don't reach into Jenkins' internal structure, just request it from the service and cache it
This is safe, because Jenkins serves the CLI binary unauthenticated even if global authentication is enabled.

Request jenkins-cli.jar directly from jenkins

---

jenkins/cli.sls
jenkins/jobs.sls
jenkins/map.jinja
jenkins/plugins.sls

This depends on #35 
Much like declaratively installing plugins, this PR adds the ability to declaratively define jobs from XML files on-disk.
Example pillar:
```
jenkins:
lookup:
[...]
jobs:
installed:
Master: /srv/extra/jenkins/jobs/Master.xml
Tasks: /srv/extra/jenkins/jobs/Tasks.xml
Publish: /srv/extra/jenkins/jobs/Publish.xml
```
The one thing this doesn't support is `salt://` URLs, since it's not part of my use case. (`/srv/extra/jenkins` is a private git repo, containing pipeline particulars and secrets)

Jenkins jobs

---

jenkins/files/nginx.conf

Won't fail anymore on distros launching jenkins hardcoded on other ports than 8080. ArchLinux may be a sample

make use of jenkins_port in nginx.conf

---

jenkins/init.sls
jenkins/map.jinja

Needed to remove the deb source, and didn't find it where it would be expected.  Salt, and most other sources wind up going in the default /etc/apt/sources.list.d directory.
For debian family OS:
Add pkgrepo.managed.file handling to init.sls
Set default in map.jinja to /etc/apt/sources.list.d/jenkins-ci.list as per Debian/Ubuntu default

Change apt source file location

---

jenkins/init.sls
jenkins/map.jinja

This https://github.com/saltstack-formulas/jenkins-formula/pull/37/files has become stale and not merged, sending a new copy so it could be merged right away.
Adds support for stable release for debian and redhat.
closes https://github.com/saltstack-formulas/jenkins-formula/issues/9
@marianuspotratz @gravyboat

Add support for stable jenkins

---

jenkins/cli.sls
jenkins/jobs.sls
jenkins/macros.jinja
jenkins/map.jinja
jenkins/plugins.sls

Remoting connection mode is deprecated due to security reasons and you should use ssh or http connection mode instead. 
For `ssh` connection mode you have to configure `cli.ssh_user`, for `http` (default connection mode) `cli.http_auth` (format username:apitoken or username:password). `remoting` connection mode is available too, but you have to login via cli before calling any other commands.
`http` is default connection mode and it should work as is, for `ssh` you have to enable SSHD port in Global security configuration, for `remoting` you have to enable CLI over remoting.
If you have cached older jenkins-cli.jar version, you have to download new one (delete cached file).
See https://jenkins.io/doc/book/managing/cli/#using-the-cli-client for details.
Macros are refactored to seperate …

Added support for http/ssh connection mode for CLI client

---

.kitchen.yml
jenkins/cli.sls
jenkins/defaults.yaml
jenkins/map.jinja
jenkins/osmap.yaml

An attempt to work around the inconsistent ncat flags using another optional pillar value - preserves default behavior, tested on CentOS 7 (with nmap-ncat) and `netcat_flag` set to `--recv-only`

#47: make netcat flag configurable

---

jenkins/defaults.yaml

Default values without '' breaks config file for Debian in this case. They are not printed as string but interpreted to different values.

Fixed default config values

---

jenkins/jobs.sls

I've used `diff -w` to build an `unless` clause so that this only happens when the files really change. As the jenkins cli will modify the XML provided, stripping any line feeds at the end etc, I found using `diff -w` slightly easier to work with.
fixes #78
- Jobs were not automatically updated when applying state with edits to the xml files
- If the job/name/config.xml and jobDefFolder/name.xml differ, update the job

Automatically update job configurations

---

jenkins/files/Debian/jenkins.conf

The $JAVA variable is missing from jenkins.conf for Debian. This causes
the service to fail to start, due to the Java executable path not being
present.

Add Java executable path to Debian config

---

jenkins/defaults.yaml
jenkins/files/Debian/jenkins.conf

* The init script for Debian expects DAEMON to be set, so have it in the defaults file and configurable.
* Set JENKINS_HOME on top of the file allow it to be referenced in other config options.

Debian fixes

---

README.rst
jenkins/jobs.sls

Ensure Python 3.6 compatibility.
Tested on FreeBSD 11.2 with `salt-ssh` to Ubuntu 18.04.

iteritems() -> items() (Python 3.6)

---

jenkins/init.sls

**Issue**:
If we change Jenkins user from default user 'jenkins' to any other user in pillars, the Jenkins service won't start because ownership of /var/log/jenkins and /var/cache/jenkins is not updated to the new user. In this case, Jenkins service status will be.
`
jenkins dead but pid file exists
`
**Fix:**
This commit updates ownership of both  '/var/log/jenkins' and '/var/cache/jenkins'  along with Jenkins home directory, to the user/group mentioned in pillars

Fix for 'Jenkins service won't start if Jenkins user is not default'

---

jenkins/jobs.sls

You require jenkins_updates_file in jobs.sls but its only available on plugins.sls

fix wrong requisite in jobs.sls

---

jenkins/defaults.yaml
jenkins/init.sls

This PR is a minor change, jenkins moved to a new main domain which caused the formula to fail.
Updated domain jenkins-ci.org to jenkins.io

Correct domain for packages and updates

---

jenkins/init.sls

Jenkins changed their repo key, so updated key URL and added key path for Debian due to deprecation od apt-key.

Updated apt repo key
